data_dir: './data/img/'
chara_nums: 11172
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 80
num_channels: 128
num_res_blocks: 3
lr: 0.00005
batch_size: 4
log_interval: 250
save_interval: 30000
train_step: 420000
attention_resolutions: '40, 20, 10'
sty_encoder_path: './pretrained_models/korean_styenc.ckpt'
model_save_dir: './trained_models'
stroke_path: './korean_comp.txt'
classifier_free: False
total_train_step: 800000
resume_checkpoint: "./trained_models/1_korea_mom_pure/ema_0.9999_090000.pt"
exp_name: '1_korea_mom_pure'