dropout: 0.1
chara_nums: 11172
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 80
num_channels: 128
num_res_blocks: 3
batch_size: 1
num_samples: 5
attention_resolutions: '40, 20, 10'
use_ddim: True
timestep_respacing: ddim25
stroke_path: './korean_comp.txt'
model_path: './trained_models/1_korea_mom_pure/model190000.pt'
sty_img_path: './data/img/gmarket/00011.png'
total_txt_file: './total_kor.txt'
gen_txt_file: './gen_char_kor.txt'
img_save_path: './result'
classifier_free: True
cont_scale: 3.0
sk_scale: 3.0