decomposition: data/kor/decomposition.json
primals: data/kor/primals.json

trainer:
  resume:
  work_dir: ./result/lf2

dset:
  train:
    source_path: data/kor/source.ttf
    source_ext: ttf
    
gen:
  emb_dim: 8
